# Generated by Django 5.2.17 on 2026-08-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iac', '0002_terraformstack_last_cmdb_sync_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terraformstack',
            name='cloud_provider',
            field=models.CharField(choices=[('aliyun', '阿里云'), ('huaweicloud', '华为云'), ('tencent', '腾讯云'), ('aws', 'AWS')], max_length=32, verbose_name='云厂商'),
        ),
    ]
